// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avocvdaqlgnvrqfcfvwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2b2N2ZGFxbGdudnJxZmNmdnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjY1NDgsImV4cCI6MjA3NDM0MjU0OH0.hg_J38VChqAS3qhA3F8HzdaqKLI5vnzS9mLolSExdAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});